FROM ghcr.io/dbt-labs/dbt-postgres:1.7.2

WORKDIR /usr/app

COPY . .

RUN mkdir -p ~/.dbt

RUN cp profiles.yml ~/.dbt/profiles.yml

ENV DBT_PROFILES_DIR=/root/.dbt

ENTRYPOINT ["tail", "-f", "/dev/null"]